//
//  MainWorker.swift
//  Clean-Architecture
//
//  Created by Surachat Yaitammasan on 20/9/2563 BE.
//  Copyright (c) 2563 Surachat Yaitammasan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker
{
  func doSomeWork()
  {
  }
}
