//
//  MainPresenter.swift
//  Clean-Architecture
//
//  Created by Surachat Yaitammasan on 20/9/2563 BE.
//  Copyright (c) 2563 Surachat Yaitammasan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentSomething(response: Main.Login.Response)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Main.Login.Response)
  {
    let viewModel = Main.Login.ViewModel(success: response.success)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
