//
//  MainViewController.swift
//  Clean-Architecture
//
//  Created by Surachat Yaitammasan on 20/9/2563 BE.
//  Copyright (c) 2563 Surachat Yaitammasan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDisplayLogic: class
{
    func displaySomething(viewModel: Main.Login.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic
{
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    @IBOutlet weak var nameTextField: UITextField!
    
    @IBAction func goHomeButton(_ sender: UIButton) {
        doSomething()
    }
    
    func doSomething()
    {
        let request = Main.Login.Request(name: nameTextField.text!)
        interactor?.goHome(request: request)
    }
    
    func displaySomething(viewModel: Main.Login.ViewModel)
    {
        if viewModel.success {
            router?.routeToSomewhere(segue: nil)
        }
        else {
            displayAlert()
        }
        
    }
    
    func displayAlert() {
        let alert = UIAlertController(title: "Pleas tell your name.", message: "If you want to go next page tell your name.", preferredStyle: .alert)

        alert.addAction(UIAlertAction(title: "Okay", style: .cancel, handler: nil))

        self.present(alert, animated: true)
    }
}
