//
//  DetailPresenter.swift
//  Clean-Architecture
//
//  Created by Surachat Yaitammasan on 21/9/2563 BE.
//  Copyright (c) 2563 Surachat Yaitammasan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentSomething(response: Detail.Something.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Detail.Something.Response)
  {
    let helloworld = "Welcome \(response.name), nice to meet you"
    let viewModel = Detail.Something.ViewModel(name: helloworld)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
